// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_deplay_screen_init(void)
{
ui_deplay = lv_obj_create(NULL);
lv_obj_clear_flag( ui_deplay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_deplay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_deplay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wificonfigbt = lv_imgbtn_create(ui_deplay);
lv_imgbtn_set_src(ui_wificonfigbt, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_botttt_png, NULL);
lv_obj_set_height( ui_wificonfigbt, 40);
lv_obj_set_width( ui_wificonfigbt, LV_SIZE_CONTENT);  /// 2
lv_obj_set_x( ui_wificonfigbt, 204 );
lv_obj_set_y( ui_wificonfigbt, 95 );
lv_obj_set_align( ui_wificonfigbt, LV_ALIGN_CENTER );

ui_led1 = lv_obj_create(ui_deplay);
lv_obj_set_width( ui_led1, 30);
lv_obj_set_height( ui_led1, 32);
lv_obj_set_x( ui_led1, 205 );
lv_obj_set_y( ui_led1, -42 );
lv_obj_set_align( ui_led1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_led1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_led2 = lv_obj_create(ui_deplay);
lv_obj_set_width( ui_led2, 30);
lv_obj_set_height( ui_led2, 33);
lv_obj_set_x( ui_led2, 205 );
lv_obj_set_y( ui_led2, 3 );
lv_obj_set_align( ui_led2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_led2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_led3 = lv_obj_create(ui_deplay);
lv_obj_set_width( ui_led3, 30);
lv_obj_set_height( ui_led3, 30);
lv_obj_set_x( ui_led3, 205 );
lv_obj_set_y( ui_led3, 50 );
lv_obj_set_align( ui_led3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_led3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_led5 = lv_obj_create(ui_deplay);
lv_obj_set_width( ui_led5, 221);
lv_obj_set_height( ui_led5, 226);
lv_obj_set_x( ui_led5, 40 );
lv_obj_set_y( ui_led5, -12 );
lv_obj_set_align( ui_led5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_led5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_led5, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_led5, lv_color_hex(0x00FE24), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_led5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar1 = lv_bar_create(ui_deplay);
lv_bar_set_range(ui_Bar1, 0,3);
lv_obj_set_width( ui_Bar1, 129);
lv_obj_set_height( ui_Bar1, 23);
lv_obj_set_x( ui_Bar1, -119 );
lv_obj_set_y( ui_Bar1, 78 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFD0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_led4 = lv_obj_create(ui_deplay);
lv_obj_set_width( ui_led4, 26);
lv_obj_set_height( ui_led4, 24);
lv_obj_set_x( ui_led4, 115 );
lv_obj_set_y( ui_led4, -119 );
lv_obj_set_align( ui_led4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_led4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_deplay);
lv_img_set_src(ui_Image2, &ui_img_602835949);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 480
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 272
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Buttondow = lv_btn_create(ui_deplay);
lv_obj_set_width( ui_Buttondow, 40);
lv_obj_set_height( ui_Buttondow, 39);
lv_obj_set_x( ui_Buttondow, 72 );
lv_obj_set_y( ui_Buttondow, 112 );
lv_obj_set_align( ui_Buttondow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Buttondow, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Buttondow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Buttondow, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buttondow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Buttondow, &ui_img_do_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_Buttondow, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Buttondow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Buttonup = lv_btn_create(ui_deplay);
lv_obj_set_width( ui_Buttonup, 40);
lv_obj_set_height( ui_Buttonup, 40);
lv_obj_set_x( ui_Buttonup, 134 );
lv_obj_set_y( ui_Buttonup, 111 );
lv_obj_set_align( ui_Buttonup, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Buttonup, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Buttonup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Buttonup, lv_color_hex(0x010000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buttonup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Buttonup, &ui_img_up_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_Buttonup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Buttonup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settimg1 = lv_btn_create(ui_deplay);
lv_obj_set_width( ui_settimg1, 48);
lv_obj_set_height( ui_settimg1, 20);
lv_obj_set_x( ui_settimg1, -86 );
lv_obj_set_y( ui_settimg1, 115 );
lv_obj_set_align( ui_settimg1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_settimg1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_settimg1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_settimg1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_settimg1, lv_color_hex(0xFEB200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settimg1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_deplay);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -86 );
lv_obj_set_y( ui_Label2, 116 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"TIMING");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFDFAFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settimg2 = lv_btn_create(ui_deplay);
lv_obj_set_width( ui_settimg2, 48);
lv_obj_set_height( ui_settimg2, 20);
lv_obj_set_x( ui_settimg2, -140 );
lv_obj_set_y( ui_settimg2, 115 );
lv_obj_set_align( ui_settimg2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_settimg2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_settimg2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_settimg2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_settimg2, lv_color_hex(0x1BC758), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settimg2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_deplay);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -139 );
lv_obj_set_y( ui_Label1, 116 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"MODE");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFDFAFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch2 = lv_switch_create(ui_deplay);
lv_obj_set_width( ui_Switch2, 50);
lv_obj_set_height( ui_Switch2, 23);
lv_obj_set_x( ui_Switch2, -193 );
lv_obj_set_y( ui_Switch2, 115 );
lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xC01F1F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_Label3 = lv_label_create(ui_deplay);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 184 );
lv_obj_set_y( ui_Label3, -119 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Thu 14 Dec 17:59");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &ui_font_kanit28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_deplay);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 39 );
lv_obj_set_y( ui_Label6, -40 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"000");
lv_obj_set_style_text_font(ui_Label6, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_deplay);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 39 );
lv_obj_set_y( ui_Label7, 13 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"000");
lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_deplay);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -148 );
lv_obj_set_y( ui_Label8, -24 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"00");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &ui_font_kanit30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_deplay);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -147 );
lv_obj_set_y( ui_Label9, 35 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"00");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &ui_font_kanit30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_deplay);
lv_img_set_src(ui_Image3, &ui_img_filter_2_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image3, -10 );
lv_obj_set_y( ui_Image3, 113 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,100);

lv_obj_add_event_cb(ui_wificonfigbt, ui_event_wificonfigbt, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Buttondow, ui_event_Buttondow, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Buttonup, ui_event_Buttonup, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settimg1, ui_event_settimg1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settimg2, ui_event_settimg2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);

}
