// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT settimg

lv_obj_t *ui_settimg_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_settimg;
cui_settimg = lv_btn_create(comp_parent);
lv_obj_set_width( cui_settimg, 51);
lv_obj_set_height( cui_settimg, 23);
lv_obj_set_x( cui_settimg, -88 );
lv_obj_set_y( cui_settimg, 118 );
lv_obj_set_align( cui_settimg, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_settimg, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_settimg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_settimg, lv_color_hex(0xFEB200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_settimg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SETTIMG_NUM);
children[UI_COMP_SETTIMG_SETTIMG] = cui_settimg;
lv_obj_add_event_cb(cui_settimg, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_settimg, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_settimg_create_hook(cui_settimg);
return cui_settimg; 
}

