// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_deplay
void ui_deplay_screen_init(void);
extern lv_obj_t *ui_deplay;
void ui_event_wificonfigbt( lv_event_t * e);
extern lv_obj_t *ui_wificonfigbt;
extern lv_obj_t *ui_led1;
extern lv_obj_t *ui_led2;
extern lv_obj_t *ui_led3;
extern lv_obj_t *ui_led5;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_led4;
extern lv_obj_t *ui_Image2;
void ui_event_Buttondow( lv_event_t * e);
extern lv_obj_t *ui_Buttondow;
void ui_event_Buttonup( lv_event_t * e);
extern lv_obj_t *ui_Buttonup;
void ui_event_settimg1( lv_event_t * e);
extern lv_obj_t *ui_settimg1;
extern lv_obj_t *ui_Label2;
void ui_event_settimg2( lv_event_t * e);
extern lv_obj_t *ui_settimg2;
extern lv_obj_t *ui_Label1;
void ui_event_Switch2( lv_event_t * e);
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Image3;
// SCREEN: ui_swifiseting
void ui_swifiseting_screen_init(void);
void ui_event_swifiseting( lv_event_t * e);
extern lv_obj_t *ui_swifiseting;
extern lv_obj_t *ui_wifiseting;
void ui_event_Buttonbk1( lv_event_t * e);
extern lv_obj_t *ui_Buttonbk1;
void ui_event_Dropdown1( lv_event_t * e);
extern lv_obj_t *ui_Dropdown1;
void ui_event_TextArea5( lv_event_t * e);
extern lv_obj_t *ui_TextArea5;
extern lv_obj_t *ui_Ver;
void ui_event_Slider3( lv_event_t * e);
extern lv_obj_t *ui_Slider3;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
void ui_event_Keyboard2( lv_event_t * e);
extern lv_obj_t *ui_Keyboard2;
// SCREEN: ui_stimeseting
void ui_stimeseting_screen_init(void);
extern lv_obj_t *ui_stimeseting;
void ui_event_Buttonbk( lv_event_t * e);
extern lv_obj_t *ui_Buttonbk;
extern lv_obj_t *ui_Checkbox2;
extern lv_obj_t *ui_Checkbox1;
extern lv_obj_t *ui_Checkbox3;
extern lv_obj_t *ui_Checkbox4;
extern lv_obj_t *ui_Checkbox5;
extern lv_obj_t *ui_Checkbox6;
extern lv_obj_t *ui_Checkbox7;
void ui_event_TextArea2( lv_event_t * e);
extern lv_obj_t *ui_TextArea2;
void ui_event_TextArea1( lv_event_t * e);
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_Label4;
void ui_event_TextArea3( lv_event_t * e);
extern lv_obj_t *ui_TextArea3;
void ui_event_TextArea4( lv_event_t * e);
extern lv_obj_t *ui_TextArea4;
extern lv_obj_t *ui_Label5;
void ui_event_Keyboard1( lv_event_t * e);
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_botttt_png);   // assets\botttt.png
LV_IMG_DECLARE( ui_img_602835949);   // assets\final-arkad-08.png
LV_IMG_DECLARE( ui_img_do_png);   // assets\do.png
LV_IMG_DECLARE( ui_img_up_png);   // assets\up.png
LV_IMG_DECLARE( ui_img_filter_2_png);   // assets\Filter_2.png
LV_IMG_DECLARE( ui_img_1711361369);   // assets\back-53-48.png
LV_IMG_DECLARE( ui_img_11_png);   // assets\11.png
LV_IMG_DECLARE( ui_img_1986391116);   // assets\Cut-09.png
LV_IMG_DECLARE( ui_img_602825187);   // assets\final-arkad-02.png
LV_IMG_DECLARE( ui_img_602820839);   // assets\final-arkad-06.png
LV_IMG_DECLARE( ui_img_602819814);   // assets\final-arkad-07.png

LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_Font12);
LV_FONT_DECLARE( ui_font_Font16);
LV_FONT_DECLARE( ui_font_Font20);
LV_FONT_DECLARE( ui_font_Font48);
LV_FONT_DECLARE( ui_font_kanit28);
LV_FONT_DECLARE( ui_font_kanit30);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
