// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void fandoawe(lv_event_t * e);
void fanupupup(lv_event_t * e);
void set_mode(lv_event_t * e);
void SW_on_off_time(lv_event_t * e);
void wifi_scanning(lv_event_t * e);
void wifi_save_ssid_(lv_event_t * e);
void SSIDWIFIXX(lv_event_t * e);
void wificonnectin(lv_event_t * e);
void Timeseting_p_ep(lv_event_t * e);
void M_limi_num_on(lv_event_t * e);
void H_limi_num_on(lv_event_t * e);
void H_limi_num_off(lv_event_t * e);
void M_limi_num_off(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
